input_data:
  pv:
    pv_files_groups:
      - label: solar_sheffield_passiv
        pv_filename: 'test.nc'
        pv_metadata_filename: 'UK_PV_metadata.csv'
        get_center: false
        pv_image_size_meters_height: 10000000
        pv_image_size_meters_width: 10000000
  nwp:
    ukv:
      nwp_channels:
        - t
      nwp_image_size_pixels_height: 2
      nwp_image_size_pixels_width: 2
      nwp_zarr_path: nwp_data/test.zarr
      nwp_provider: "ukv"
      history_minutes: 60
      forecast_minutes: 120
      time_resolution_minutes: 60
      index_by_id: True
      dropout_timedeltas_minutes: [-180]
      dropout_fraction: 1.0